#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP
function display_info() {
    local subdomain=$1
    local domain=$2
    local record=$(dig +short $subdomain.$domain | head -n1)
    local record_type=$(dig +short $subdomain.$domain | awk 'NR==1{print $4}')
    echo "The subdomain $subdomain is a $record_type record and points to $record"
}

if [ $# -eq 1 ]; then
    domain=$1
    display_info www $domain
    display_info lb-01 $domain
    display_info web-01 $domain
    display_info web-02 $domain
elif [ $# -eq 2 ]; then
    subdomain=$2
    domain=$1
    display_info $subdomain $domain
else
    echo "Usage: $0 domain [subdomain]"
fi

