#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer
# Function to print DNS records

print_dns_records() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record=$(dig +short "$sub.$domain")
        record_type=$(dig +short "$sub.$domain"| grep A)
        echo "The subdomain $sub is a $record_type record and points to $record"
    done
}

# Example usage: ./dns_audit.sh example.com
# Example usage: ./dns_audit.sh example.com www
print_dns_records "$1" "$2"

