#!/usr/bin/env bash
# Copies some_page.html to remote server
if (($# < 3))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp $1 $3@$2:~/ $4 
     
fi

ssh ubuntu@34.207.63.248 'ls ~/'
