#!/usr/bin/env bash
#This script install and configure nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!'| sudo tee /var/www/html/index.html > /dev/null

