#!/usr/bin/env bash
#This script install and configure nginx
if ! command -v nginx &> /dev/null
then
    echo "Nginx is not installed. Installing now..."
    sudo apt-get update
    sudo apt-get install nginx
fi

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default


echo 'Hello World!'| sudo tee /var/www/html/index.html > /dev/null

