#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# Installs, configures, and starts the server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo tee /etc/nginx/sites-available/redirect_me << EOF
server {
    listen 80;
    server_name vestec.tech www.vestec.tech;
    rewrite ^/(.*)$ https://vestec.tech/$1 permanent;
    
}
EOF
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo service nginx restart
