#!/bin/bash
# Install Nginx
sudoapt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee  /var/www/html/index.html > /dev/null
rm /etc/nginx/sites-enabled/default
cat <<EOF > /etc/nginx/sites-available/redirect_me.conf
server {
  listen 80;
  server_name _;
  return 301 http://www.redirected.com/;
}
EOF
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/
sudo systemctl restart nginx

