#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update 
sudo apt-get install nginx -y
echo "Helo World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo cat > /etc/nginx/sites-available/default << EOF
server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}
EOF
sudo service nginx restart
