#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install nginx -y
sudo service start
sudo sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo systemctl restart nginx
