#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.7.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend vestec.tech
        bind 0:80
        default_backend nodes

backend nodes
        balance roundrobin
        server 105775-web-01 18.234.80.132:80
        server 105775-web-02 100.25.160.25:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
