#!/usr/bin/env bash
# configure haproxy load-balancing server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get update -y
sudo apt-get install -y haproxy=2.7.*
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend nodes

backend nodes
    balance roundrobin
    server node1 18.234.80.132:80 check
    server node2 100.25.160.25:80 check
EOF
sudo service haproxy restart
