#!/usr/bin/env bash
script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
current_date = $(date + '%d-%m-%Y');
tar -cvzf "$(current_date)".tar.gz backup.sql

