#!/usr/bin/env bash
# This script that displays Best School 10 times

number=1
while [ $number -lt 11 ]
do
    if [ $number = 9 ];
    then
	echo "Hi"
    else
	echo "Best School"
    fi
    number=$(( number+1 ))
done
