#!/usr/bin/env bash
# This script  loops from 1 to 10 and displays :
# bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Best School for the other iterations


number=1
while [ $number -le 10 ]
do
	if [ $number = 4 ];
	then
		echo "bad luck"
	elif [ $number = 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	number=$(( number+1 ))
done