#!/usr/bin/env bash
# configures the container to listen to port 8080
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
